<h1>Registered Users</h1>
<div class="row">
    <div class="col-md-12">
        <?php if (empty($this->users)) : ?>
            <div class="alert alert-warning">
                <strong>No user registered yet. Do you want to <a href="<?php echo $this->url('page::user-registration-form') ?>">add yourself</a>?</strong>
            </div>
        <?php else: ?>
            <div class="list-group">
                <?php foreach ($this->users as $user) : ?>
                    <a href="<?php echo $this->url('page::user-todo-list', ['user_id' => $user->id]) ?>" class="list-group-item"><strong><?php echo $this->escapeHtml($user->name) ?></strong><small class="text-info">&nbsp;&nbsp;open Todos: <?php echo $user->open_todos + $user->expired_todos ?>&nbsp;&nbsp;|&nbsp;&nbsp;closed Todos:&nbsp;<?php echo $user->done_todos ?></small></a>
                <?php endforeach;?>
            </div>
        <?php endif; ?>
    </div>
</div>
