<?php
/**
 * This file is part of prooph/proophessor-do.
 * (c) 2014-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?><form method="post" enctype="multipart/form-data" action="#" onsubmit="{onFormSubmit}">
    <div class="{form-group: true, has-error: !todoIsValid}">
        <input class="form-control" type="text" name="todo" placeholder="Describe the Todo with a one liner and press Enter">
        <p if="{!todoIsValid}" class="help-block">Oops, that didn't make it. Typed to fast? The Todo should be at least 3 characters long. Please try again!</p>
        <p if="{todoIsValid}" class="help-block">The Todo will be assigned to <?php echo $this->escapeHtml($this->user->name) ?></p>
    </div>
    <input type="hidden" name="user_id" value="<?php echo $this->user->id ?>">
</form>
<script type="text/javascript">
    function (context) {

        var self = this,
            _checkValidTodo = function () {
                self.todoIsValid = _.isEmpty(validate.single(self.todo.value, {presence: true, length: {minimum: 3}}))
            };

        self.todoIsValid = true;

        self.onFormSubmit = function (e) {
            e.preventDefault();

            _checkValidTodo();

            if (self.todoIsValid) {

                var todoId = UUID();

                $.postJSON(
                    '<?php echo $this->url('command::post-todo') ?>',
                    {
                        assignee_id : self.user_id.value,
                        todo_id : todoId,
                        text : self.todo.value
                    }
                ).then(
                    function () {
                        window.location.href =
                            '<?php echo $this->url('page::user-todo-list', ['user_id' => '00000000-0000-0000-0000-000000000000']) ?>'
                                .replace('00000000-0000-0000-0000-000000000000', self.user_id.value);
                    },
                    $.failNotify
                );
            }
        }
    }
</script>
