<?php
/**
 * This file is part of prooph/proophessor-do.
 * (c) 2014-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (! $this->user) : ?>
    <h1>User cannot be found!</h1>
    <p class="alert alert-info">
        If you're coming from the registration process you can try to refresh the page. Maybe the operation took a bit longer
        than normal. If your data still isn't available please contact the support.
    </p>
<?php else : ?>
    <h1>Todos assigned to <?php echo $this->escapeHtml($this->user->name) ?></h1>
    <div class="row">
        <user-todo-list></user-todo-list>
    </div>
    <script type="text/javascript">

        <?php echo $this->riotTag('riot::user-todo-list') ?>
        <?php echo $this->riotTag('riot::user-todo') ?>

        var UserTodoList = ProophRiot.App.create({
            userId : '<?php echo $this->user->id;  ?>',
            TodoStore : {
                getAll : function () {
                    return JSON.parse('<?php echo json_encode($this->todos) ?>');
                }
            }
        });

        $(function () {
            UserTodoList.bootstrap("user-todo-list").ready();
        });
    </script>
<?php endif; ?>
