<?php
/**
 * This file is part of prooph/proophessor-do.
 * (c) 2014-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?><h1>Register a new User</h1>
<div class="row">
    <div class="col-md-12">
        <user-form></user-form>
    </div>
</div>
<script type="text/javascript">

    <?php echo $this->riotTag('riot::user-form') ?>

    var UserForm = ProophRiot.App.create();

    $(function () {
        UserForm.bootstrap("user-form").ready();
    });
</script>
