<?php
/**
 * This file is part of prooph/proophessor-do.
 * (c) 2014-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$this->headTitle('404 Not Found'); ?>

<h1>Oops!</h1>
<h2>This is awkward.</h2>
<p>We encountered a 404 Not Found error.</p>
<p>
    You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
    or head back to <a href="<?php echo $this->url('page::home') ?>">Home</a>.
</p>
