<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('proophessor-do')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(/*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')*/)
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.slate.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/global.settings.js')
            ->prependFile($this->basePath() . '/js/notify.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/underscore.string.js')
            ->prependFile($this->basePath() . '/js/lodash.js')
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">proophessor-do</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="row">
            <div class="hidden-xs col-sm-3 col-md-2">
                <div id="sidebar-left" data-spy="affix" data-offset-top="60">
                    <ul class="sidebar-nav">
                        <li>
                            <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Welcome Screen') ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('user_list')?>"><?php echo $this->translate('Manage Users') ?></a>
                        </li>
                        <li>
                            <a href="#/create"><?php echo $this->translate('Manage Todos') ?></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-7 col-md-8">
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; 2014 - <?php echo date('Y') ?> by prooph software GmbH. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
            <div class="col-sm-2 col-md-2">
                <?php if (isset($this->sidebar_right)) echo $this->sidebar_right; ?>
            </div>
        </div>
        <?php if ($this->includeRiotJs) : ?>
            <?php echo $this->inlineScript()
                //->prependFile($this->basePath() . '/js/prooph.link.riot.app.js')
                ->prependFile($this->basePath() . '/js/riot.js')
            ?>
        <?php else: ?>
            <?php echo $this->inlineScript(); ?>
        <?php endif; ?>
    </body>
</html>
