<h1>Register a new User</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post" action="" enctype="multipart/form-data">
            <div class="form-group <?php echo ($this->invalidName)? 'has-error' : ''?>">
                <label class="control-label" for="name">Username</label>
                <input name="username" type="text" class="form-control" value="<?php echo $this->escapeHtmlAttr($this->name)?>">
                <?php if ($this->invalidNameMsg) :?>
                    <p class="help-block"><?php echo $this->invalidNameMsg ?></p>
                <?php endif; ?>
            </div>
            <div class="form-group <?php echo ($this->invalidEmail)? 'has-error' : ''?>">
                <label class="control-label" for="email">Email</label>
                <input name="email" type="email" value="<?php echo $this->escapeHtmlAttr($this->email)?>" class="form-control">
                <?php if ($this->invalidEmailMsg) :?>
                    <p class="help-block"><?php echo $this->invalidEmailMsg ?></p>
                <?php else: ?>
                    <p class="help-block">The email is used to send you reminders for your Todos.</p>
                <?php endif; ?>
            </div>
            <div class="btn-group pull-right">
                <input type="submit" class="btn btn-success" name="ok" value="register user">
                <a href="<?php echo $this->url('user_list') ?>" class="btn btn-default">cancel</a>
            </div>
        </form>

    </div>
</div>