<?php
/**
 * This file is part of prooph/proophessor-do.
 * (c) 2014-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>proophessor-do</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/style.css">


    <script language="javascript" type="text/javascript" src="/js/lodash.js"></script>
    <script language="javascript" type="text/javascript" src="/js/underscore.string.js"></script>
    <script language="javascript" type="text/javascript" src="/js/jquery.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/notify.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/validate.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/jquery.plugins.js"></script>
    <script language="javascript" type="text/javascript" src="/js/moment.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/bootstrap-datetimepicker.js"></script>
    <script language="javascript" type="text/javascript" src="/js/uuid.js"></script>
    <script language="javascript" type="text/javascript" src="/js/riot.min.js"></script>
    <script language="javascript" type="text/javascript" src="/js/prooph.riot.app.js"></script>

</head>
<body>
<nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="prooph-logo">
                <img src="/img/prooph-logo.svg"/>
            </a>
            <a class="navbar-brand" href="<?php echo $this->url('page::home') ?>">
                proophessor-do
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

            </ul>
        </div><!--/.nav-collapse  -->
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="hidden-xs col-sm-3 col-md-2">
            <div id="sidebar-left" data-spy="affix" data-offset-top="60">
                <ul class="nav nav-pills nav-stacked">
                    <li>
                        <a href="<?php echo $this->url('page::home') ?>">Welcome Screen</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('page::user-list') ?>">Manage Todos</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-sm-7 col-md-8">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by prooph software GmbH. All rights reserved.</p>
            </footer>
        </div>
        <div class="hidden-xs col-sm-2">
            <?php if (isset($this->sidebar_right)) {
                echo $this->sidebar_right;
            } ?>
        </div>
    </div>
</div>
</body>
</html>
